/* DIRI accessibility preferences and read-aloud tools. */
'use strict';
(function () {
  const KEY = 'diri-a11y-state-v2';
  const defaults = { textSize:0,lineHeight:0,textSpacing:0,readableFont:false,dyslexiaFont:false,highlightHeadings:false,highlightLinks:false,highlightButtons:false,hideImages:false,tooltips:false,stopAnimations:false,colorMode:'default',saturation:'normal',readingGuide:false,readingMask:false,cursor:'default',speechRate:1 };
  const profiles = {
    visual:{textSize:2,lineHeight:2,readableFont:true,highlightLinks:true,highlightButtons:true,colorMode:'high'},
    seizure:{stopAnimations:true,saturation:'low'},
    colorVision:{colorMode:'color-vision',highlightLinks:true,highlightButtons:true},
    adhd:{readableFont:true,highlightHeadings:true,highlightButtons:true,readingGuide:true,stopAnimations:true},
    dyslexia:{dyslexiaFont:true,textSize:1,lineHeight:2,textSpacing:2,readingGuide:true},
    learning:{readableFont:true,textSize:1,lineHeight:1,highlightHeadings:true,highlightButtons:true,tooltips:true}
  };
  const profileNames={visual:'Visual support',seizure:'Seizure-safe',colorVision:'Colour vision',adhd:'Focus support',dyslexia:'Dyslexia support',learning:'Learning support'};
  let state=load(),panel,toggle,guide,mask,synth=null,queue=[],queueIndex=0,speaking=false,paused=false,speechMark=null;

  function load(){try{return Object.assign({},defaults,JSON.parse(localStorage.getItem(KEY)||'{}'));}catch(_){return Object.assign({},defaults);}}
  function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch(_){}}
  function announce(message){let box=document.getElementById('diri-announcer');if(!box){box=document.createElement('div');box.id='diri-announcer';box.className='diri-announcer';box.setAttribute('role','status');box.setAttribute('aria-live','polite');document.body.appendChild(box);}box.textContent='';setTimeout(function(){box.textContent=message;},10);}
  function skipLink(){if(document.querySelector('.diri-skip-link'))return;const link=document.createElement('a');link.href='#main-content';link.className='diri-skip-link';link.textContent='Skip to main content';document.body.insertBefore(link,document.body.firstChild);if(!document.getElementById('main-content')){const main=document.querySelector('main,[role="main"],.page-content,.hero,.section');if(main)main.id='main-content';}}
  function className(key){return 'diri-a11y-'+key.replace(/[A-Z]/g,function(letter){return '-'+letter.toLowerCase();});}
  function tools(){if(!guide){guide=document.createElement('div');guide.className='diri-reading-guide';guide.hidden=true;guide.setAttribute('aria-hidden','true');document.body.appendChild(guide);}if(!mask){mask=document.createElement('div');mask.className='diri-reading-mask';mask.hidden=true;mask.setAttribute('aria-hidden','true');document.body.appendChild(mask);}}
  function tooltips(on){document.querySelectorAll('a,button,input,select,textarea').forEach(function(el){if(el.closest('.diri-a11y-panel')||el===toggle)return;if(on&&!el.title){const label=el.getAttribute('aria-label')||el.textContent.trim()||el.placeholder||el.name;if(label){el.title=label;el.dataset.a11yGeneratedTitle='true';}}else if(!on&&el.dataset.a11yGeneratedTitle==='true'){el.removeAttribute('title');delete el.dataset.a11yGeneratedTitle;}});}
  function apply(silent){const root=document.documentElement;root.dataset.a11yTextSize=state.textSize;root.dataset.a11yLineHeight=state.lineHeight;root.dataset.a11yTextSpacing=state.textSpacing;root.dataset.a11yColor=state.colorMode;root.dataset.a11ySaturation=state.saturation;root.dataset.a11yCursor=state.cursor;['readableFont','dyslexiaFont','highlightHeadings','highlightLinks','highlightButtons','hideImages','tooltips','stopAnimations','readingGuide','readingMask'].forEach(function(key){root.classList.toggle(className(key),!!state[key]);});tooltips(state.tooltips);tools();guide.hidden=!state.readingGuide;mask.hidden=!state.readingMask;save();updatePanel();if(!silent)announce('Accessibility settings updated');}
  function reset(){stopReading();state=Object.assign({},defaults);apply(true);announce('Accessibility settings reset');}
  function matchProfile(key){return Object.keys(profiles[key]).every(function(prop){return state[prop]===profiles[key][prop];});}
  function profile(key){const remove=matchProfile(key);state=Object.assign({},defaults,remove?{}:profiles[key],{speechRate:state.speechRate});apply(true);announce(profileNames[key]+(remove?' profile removed':' profile applied'));}
  function speakable(){const main=document.querySelector('main,[role="main"],#main-content,.page-content,.hero,.section');if(!main)return[];const result=[];main.querySelectorAll('h1,h2,h3,h4,h5,h6,p,li,blockquote,td,th').forEach(function(el){if(el.hidden||el.getAttribute('aria-hidden')==='true'||!el.offsetParent)return;const text=el.textContent.trim();if(text.length>2)result.push({text:/^H[1-6]$/.test(el.tagName)?'Heading: '+text:text,element:el});});return result;}
  function speak(block){if(!synth||!block)return;if(speechMark)speechMark.classList.remove('diri-speech-highlight');speechMark=block.element;speechMark.classList.add('diri-speech-highlight');speechMark.scrollIntoView({behavior:state.stopAnimations?'auto':'smooth',block:'center'});const utterance=new SpeechSynthesisUtterance(block.text);utterance.rate=state.speechRate;const voices=synth.getVoices();utterance.voice=voices.find(function(v){return v.lang.indexOf('en')===0&&v.localService;})||voices.find(function(v){return v.lang.indexOf('en')===0;})||null;utterance.onend=function(){queueIndex++;if(queueIndex<queue.length)speak(queue[queueIndex]);else finishReading();};utterance.onerror=finishReading;speaking=true;paused=false;synth.speak(utterance);updateReader();}
  function read(){if(!('speechSynthesis'in window))return announce('Read aloud is not supported by this browser');synth=window.speechSynthesis;if(speaking&&!paused){synth.pause();paused=true;updateReader();return announce('Reading paused');}if(paused){synth.resume();paused=false;updateReader();return announce('Reading resumed');}queue=speakable();queueIndex=0;if(!queue.length)return announce('No readable content was found');speak(queue[0]);}
  function stopReading(){if(synth)synth.cancel();if(speechMark)speechMark.classList.remove('diri-speech-highlight');speechMark=null;queue=[];queueIndex=0;speaking=false;paused=false;updateReader();}
  function finishReading(){if(speechMark)speechMark.classList.remove('diri-speech-highlight');speechMark=null;speaking=false;paused=false;updateReader();}
  function speed(){const options=[0.75,1,1.25];state.speechRate=options[(options.indexOf(state.speechRate)+1)%options.length];save();updateReader();announce('Reading speed '+state.speechRate+' times');}
  function pBtn(key,icon){return '<button class="diri-a11y-profile" data-profile="'+key+'" aria-pressed="false"><span aria-hidden="true">'+icon+'</span><span>'+profileNames[key]+'</span><small>Preset</small></button>';}
  function tBtn(key,label,icon){return '<button class="diri-a11y-option" data-toggle="'+key+'" aria-pressed="false"><span aria-hidden="true">'+icon+'</span><span>'+label+'</span></button>';}
  function cBtn(key,value,label,icon){return '<button class="diri-a11y-option" data-choice="'+key+':'+value+'" aria-pressed="false"><span aria-hidden="true">'+icon+'</span><span>'+label+'</span></button>';}
  function levels(key,label,icon){return '<div class="diri-a11y-level"><span class="diri-a11y-level-title"><span aria-hidden="true">'+icon+'</span>'+label+'</span><div role="group" aria-label="'+label+'">'+[1,2,3].map(function(n){return '<button data-level="'+key+':'+n+'" aria-pressed="false">'+('+'.repeat(n))+'</button>';}).join('')+'</div></div>';}
  function build(){toggle=document.createElement('button');toggle.className='diri-a11y-toggle';toggle.setAttribute('aria-label','Open accessibility preferences');toggle.setAttribute('aria-expanded','false');toggle.innerHTML='<svg aria-hidden="true" viewBox="0 0 24 24"><circle cx="12" cy="4" r="2"/><path d="M5 8h14M12 6v6m0 0-4 8m4-8 4 8"/></svg>';document.body.appendChild(toggle);
    panel=document.createElement('aside');panel.className='diri-a11y-panel';panel.setAttribute('role','dialog');panel.setAttribute('aria-label','Accessibility preferences');panel.setAttribute('aria-hidden','true');panel.innerHTML=
    '<header class="diri-a11y-header"><div><span class="diri-a11y-eyebrow">Personalise DIRI</span><strong>Accessibility preferences</strong></div><button data-close aria-label="Close accessibility preferences">&times;</button></header>'+
    '<div class="diri-a11y-actions"><button data-reset>↻ Reset all</button><button data-read>▶ Read page</button><button data-stop hidden>■ Stop</button><button data-speed>1× speed</button></div><div class="diri-a11y-body">'+
    '<section class="diri-a11y-section"><div class="diri-a11y-section-heading"><div><span>Quick profiles</span><small>Each preset activates recommended controls below.</small></div></div><div class="diri-a11y-profile-grid">'+pBtn('visual','◉')+pBtn('seizure','ϟ')+pBtn('colorVision','◐')+pBtn('adhd','◎')+pBtn('dyslexia','Aa')+pBtn('learning','▤')+'</div></section>'+
    '<section class="diri-a11y-section"><div class="diri-a11y-section-heading"><span>Content and type</span></div><div class="diri-a11y-options-grid">'+tBtn('readableFont','Readable font','A')+tBtn('dyslexiaFont','Dyslexia-friendly font','Aa')+tBtn('highlightHeadings','Highlight headings','H')+tBtn('highlightLinks','Highlight links','↗')+tBtn('highlightButtons','Highlight buttons','▣')+tBtn('hideImages','Hide images','▧')+tBtn('tooltips','Helpful labels','?')+tBtn('stopAnimations','Stop animations','■')+'</div>'+levels('textSize','Text size','Tt')+levels('lineHeight','Line height','↕')+levels('textSpacing','Text spacing','↔')+'</section>'+
    '<section class="diri-a11y-section"><div class="diri-a11y-section-heading"><span>Colour and contrast</span></div><div class="diri-a11y-options-grid">'+cBtn('colorMode','dark','Dark contrast','◒')+cBtn('colorMode','light','Light contrast','☀')+cBtn('colorMode','invert','Invert colours','◑')+cBtn('colorMode','color-vision','Colour-safe palette','◉')+cBtn('colorMode','high','High contrast','◐')+cBtn('saturation','high','High saturation','●')+cBtn('saturation','low','Low saturation','◌')+cBtn('saturation','mono','Monochrome','◍')+'</div></section>'+
    '<section class="diri-a11y-section"><div class="diri-a11y-section-heading"><span>Focus and orientation</span></div><div class="diri-a11y-options-grid">'+tBtn('readingGuide','Reading guide','━')+tBtn('readingMask','Reading mask','▰')+cBtn('cursor','black','Large dark cursor','➤')+cBtn('cursor','white','Large light cursor','➤')+'</div></section></div>';document.body.appendChild(panel);
    toggle.addEventListener('click',open);panel.querySelector('[data-close]').addEventListener('click',close);panel.querySelector('[data-reset]').addEventListener('click',reset);panel.querySelector('[data-read]').addEventListener('click',read);panel.querySelector('[data-stop]').addEventListener('click',stopReading);panel.querySelector('[data-speed]').addEventListener('click',speed);
    panel.addEventListener('click',function(e){const pb=e.target.closest('[data-profile]'),tb=e.target.closest('[data-toggle]'),cb=e.target.closest('[data-choice]'),lb=e.target.closest('[data-level]');if(pb)profile(pb.dataset.profile);if(tb){state[tb.dataset.toggle]=!state[tb.dataset.toggle];apply();}if(cb){const v=cb.dataset.choice.split(':');state[v[0]]=state[v[0]]===v[1]?defaults[v[0]]:v[1];apply();}if(lb){const v=lb.dataset.level.split(':'),n=Number(v[1]);state[v[0]]=state[v[0]]===n?0:n;apply();}});
    document.addEventListener('keydown',function(e){if(e.key==='Escape'&&panel.classList.contains('open'))close();});document.addEventListener('pointermove',function(e){if(guide)guide.style.top=e.clientY+'px';if(mask)mask.style.top=Math.max(0,e.clientY-55)+'px';});}
  function open(){panel.classList.add('open');panel.setAttribute('aria-hidden','false');toggle.setAttribute('aria-expanded','true');panel.querySelector('[data-close]').focus();}
  function close(){panel.classList.remove('open');panel.setAttribute('aria-hidden','true');toggle.setAttribute('aria-expanded','false');toggle.focus();}
  function updateReader(){if(!panel)return;panel.querySelector('[data-read]').textContent=paused?'▶ Resume':speaking?'❚❚ Pause':'▶ Read page';panel.querySelector('[data-stop]').hidden=!speaking;panel.querySelector('[data-speed]').textContent=state.speechRate+'× speed';}
  function updatePanel(){if(!panel)return;panel.querySelectorAll('[data-profile]').forEach(function(b){b.setAttribute('aria-pressed',matchProfile(b.dataset.profile));});panel.querySelectorAll('[data-toggle]').forEach(function(b){b.setAttribute('aria-pressed',!!state[b.dataset.toggle]);});panel.querySelectorAll('[data-choice]').forEach(function(b){const v=b.dataset.choice.split(':');b.setAttribute('aria-pressed',state[v[0]]===v[1]);});panel.querySelectorAll('[data-level]').forEach(function(b){const v=b.dataset.level.split(':');b.setAttribute('aria-pressed',state[v[0]]===Number(v[1]));});updateReader();}
  function init(){skipLink();build();tools();apply(true);if('speechSynthesis'in window)synth=window.speechSynthesis;window.addEventListener('beforeunload',stopReading);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
